[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "banano_fr"
authors = [{name = "Julien#4403 and #:flag_fr:-la-jungle", email = "None"}]
dynamic = ["version", "description"]
